name: Efficient PR job

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

# Cancel any previous runs of this workflow for the same PR.
concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest
    # Do not run this job if the PR is a draft.
    if: "!github.event.pull_request.draft"
    steps:
      - name: Run tests
        run:  sleep 10 && echo "Done! 👍"